# Site settings
title: CIS 125 Fall 2015
email: daniel.neumann@indwes.edu
description: > # this means to ignore newlines until "baseurl:"
  Hi everyone. This is the blog website for our class. It is actually 
  a repository on GitHub. You can set up your own on github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iwu-cis-125.github.io/" # the base hostname & protocol for your site
twitter_username: eclecticpen
github_username:  dkneuma

# Build settings
markdown: kramdown
